apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-redis
  template:
    metadata:
      labels:
        app: restaurant-redis
    spec:
      containers:
        - name: redis
          image: redis:alpine
          ports:
            - containerPort: 6379
          volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: redis-pvc
