# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: fastfood-ingress
#   annotations:
#     kubernetes.io/ingress.class: alb
#     alb.ingress.kubernetes.io/scheme: internet-facing
#     alb.ingress.kubernetes.io/target-type: ip
#     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
#     alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:156041436605:certificate/2c3b8182-9538-4570-ae9a-cd1a5e62a8ec
#     alb.ingress.kubernetes.io/ssl-redirect: '443'
# spec:
#   rules:
#     - host: api.tadeutupinamba.com.br
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: restaurant-api-service
#                 port:
#                   number: 80