apiVersion: v1
kind: Service
metadata:
  name: restaurant-redis-service
spec:
  selector:
    app: restaurant-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  clusterIP: None
