// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package fiapRestaurantDb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Category struct {
	ID        int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Name      string
	Handle    pgtype.Text
}

type Client struct {
	ID        int32
	Name      string
	Cpf       string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Order struct {
	ID        int32
	ClientID  int32
	Status    pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type OrderItem struct {
	ID        int32
	OrderID   int32
	ProductID int32
	Quantity  int32
	Price     pgtype.Numeric
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type Payment struct {
	ID                int32
	OrderID           int32
	Status            pgtype.Text
	Method            string
	Amount            pgtype.Numeric
	ExternalReference pgtype.Text
	QrData            pgtype.Text
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
}

type PaymentTaxSetting struct {
	ID           int32
	Name         string
	Description  pgtype.Text
	AmountType   string
	AmountValue  pgtype.Numeric
	ApplicableTo string
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Product struct {
	ID          int32
	Name        string
	Description string
	Price       pgtype.Numeric
	CategoryID  int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type ProductsImage struct {
	ID        int32
	ProductID int32
	Image     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type User struct {
	ID    int32
	Name  string
	Email pgtype.Text
	Age   pgtype.Int4
}
